#!/usr/bin/env php
<?php

use JMarcher\InterpreterCommand;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

$app = new Application('PHP Assembler', 0.1);

$app->add(new InterpreterCommand);

$app->run();
